---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homework-app
  name: homework-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homework-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homework-app
    spec:
      containers:
      - image: eu.gcr.io/x-ripple-265906/homework:latest
        name: homework

