---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homework-app
  name: homework-app-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: homework-app
  type: LoadBalancer

